# Generated by Django 4.2.16 on 2024-11-19 20:21

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('config_settings', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to='sleigh.config')),
            ],
        ),
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_msg', models.CharField(max_length=255)),
                ('policy', models.CharField(choices=[('ALLOWLIST', 'Allow'), ('BLOCKLIST', 'Block'), ('ALLOWLIST_COMPILER', 'Allow Compiler')], max_length=24)),
                ('rule_type', models.CharField(choices=[('TEAMID', 'TeamID'), ('SIGNINGID', 'SigningID'), ('BINARY', 'Binary'), ('CERTIFICATE', 'Certificate')], max_length=16)),
                ('created_by', models.CharField(blank=True, max_length=64, null=True)),
                ('date_created', models.DateField(default=django.utils.timezone.now)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='sleigh.profile')),
            ],
        ),
    ]
