# Generated by Django 4.2.16 on 2024-11-20 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sleigh', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('serial_num', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('hostname', models.CharField(max_length=64)),
                ('os_version', models.CharField(max_length=16)),
                ('os_build', models.CharField(max_length=16)),
                ('model_identifier', models.CharField(max_length=16)),
                ('santa_version', models.CharField(max_length=16)),
                ('primary_user', models.CharField(max_length=64)),
                ('binary_rule_count', models.IntegerField(default=0)),
                ('certificate_rule_count', models.IntegerField(default=0)),
                ('compiler_rule_count', models.IntegerField(default=0)),
                ('transitive_rule_count', models.IntegerField(default=0)),
                ('teamid_rule_count', models.IntegerField(default=0)),
                ('signingid_rule_count', models.IntegerField(default=0)),
                ('cdhash_rule_count', models.IntegerField(default=0)),
                ('client_mode', models.CharField(max_length=16)),
                ('request_clean_sync', models.BooleanField(default=True)),
            ],
        ),
    ]
