# Generated by Django 4.2.16 on 2024-11-20 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sleigh', '0002_device'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
