# Generated by Django 4.2.16 on 2024-11-22 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sleigh', '0004_remove_config_config_settings_remove_profile_config_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='config',
            name='assignments',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='assignments',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
