# Generated by Django 4.2.16 on 2024-11-22 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sleigh', '0005_alter_config_assignments_alter_profile_assignments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='config',
            name='assignments',
            field=models.JSONField(default=list, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='assignments',
            field=models.JSONField(default=list, null=True),
        ),
    ]
