# Generated by Django 4.2.16 on 2024-12-18 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sleigh', '0007_alter_config_assignments'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='config',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='sleigh.config'),
        ),
        migrations.AddField(
            model_name='device',
            name='profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='sleigh.profile'),
        ),
    ]
