# Generated by Django 4.2.16 on 2024-12-18 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sleigh', '0008_device_config_device_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='config',
            name='assignments',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='assignments',
        ),
    ]
