# Generated by Django 4.2.16 on 2024-12-19 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sleigh', '0009_remove_config_assignments_remove_profile_assignments'),
    ]

    operations = [
        migrations.AddField(
            model_name='rule',
            name='identifer',
            field=models.CharField(default='blank', max_length=255),
            preserve_default=False,
        ),
    ]
