# Generated by Django 4.2.16 on 2024-12-19 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sleigh', '0010_rule_identifer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rule',
            name='policy',
            field=models.CharField(choices=[('ALLOWLIST', 'Allow'), ('BLOCKLIST', 'Block'), ('ALLOWLIST_COMPILER', 'Allow Compiler')], default=None, max_length=24),
        ),
        migrations.AlterField(
            model_name='rule',
            name='rule_type',
            field=models.CharField(choices=[('TEAMID', 'TeamID'), ('SIGNINGID', 'SigningID'), ('BINARY', 'Binary'), ('CERTIFICATE', 'Certificate')], default=None, max_length=16),
        ),
    ]
