# Generated by Django 4.2.16 on 2025-01-03 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sleigh', '0011_alter_rule_policy_alter_rule_rule_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('user', models.CharField(max_length=64)),
                ('action', models.CharField(max_length=256)),
            ],
        ),
    ]
