# Generated by Django 4.2.16 on 2025-01-08 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sleigh', '0013_rename_identifer_rule_identifier'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rule',
            old_name='custom_msg',
            new_name='description',
        ),
    ]
