# Generated by Django 4.2.16 on 2025-01-08 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sleigh', '0014_rename_custom_msg_rule_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_sha256', models.CharField(max_length=64, unique=True)),
                ('file_path', models.TextField()),
                ('file_name', models.CharField(max_length=255)),
                ('executing_user', models.CharField(blank=True, max_length=255, null=True)),
                ('execution_time', models.FloatField(blank=True, null=True)),
                ('loggedin_users', models.JSONField(blank=True, null=True)),
                ('current_sessions', models.JSONField(blank=True, null=True)),
                ('decision', models.CharField(max_length=50)),
                ('file_bundle_id', models.CharField(blank=True, max_length=255, null=True)),
                ('file_bundle_path', models.TextField(blank=True, null=True)),
                ('file_bundle_executable_rel_path', models.TextField(blank=True, null=True)),
                ('file_bundle_name', models.CharField(blank=True, max_length=255, null=True)),
                ('file_bundle_version', models.CharField(blank=True, max_length=50, null=True)),
                ('file_bundle_version_string', models.CharField(blank=True, max_length=50, null=True)),
                ('file_bundle_hash', models.CharField(blank=True, max_length=64, null=True)),
                ('file_bundle_hash_millis', models.FloatField(blank=True, null=True)),
                ('file_bundle_binary_count', models.IntegerField(blank=True, null=True)),
                ('pid', models.IntegerField(blank=True, null=True)),
                ('ppid', models.IntegerField(blank=True, null=True)),
                ('parent_name', models.CharField(blank=True, max_length=255, null=True)),
                ('quarantine_data_url', models.URLField(blank=True, null=True)),
                ('quarantine_referer_url', models.URLField(blank=True, null=True)),
                ('quarantine_timestamp', models.FloatField(blank=True, null=True)),
                ('quarantine_agent_bundle_id', models.CharField(blank=True, max_length=255, null=True)),
                ('signing_chain', models.JSONField(blank=True, null=True)),
                ('signing_id', models.CharField(blank=True, max_length=255, null=True)),
                ('team_id', models.CharField(blank=True, max_length=255, null=True)),
                ('cdhash', models.CharField(blank=True, max_length=64, null=True)),
                ('serial_num', models.CharField(max_length=16)),
            ],
        ),
        migrations.AddField(
            model_name='device',
            name='rules_synced',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rule',
            name='custom_msg',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='rule',
            name='custom_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
