# Generated by Django 4.2.16 on 2025-01-08 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sleigh', '0015_event_device_rules_synced_rule_custom_msg_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='file_sha256',
            field=models.CharField(max_length=64),
        ),
    ]
