# Generated by Django 4.2.16 on 2025-01-09 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sleigh', '0016_alter_event_file_sha256'),
    ]

    operations = [
        migrations.CreateModel(
            name='IgnoredEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_bundle_id', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='ignored',
            field=models.BooleanField(default=False),
        ),
    ]
