# Generated by Django 4.2.16 on 2025-01-09 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sleigh', '0017_ignoredentry_event_ignored'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='execution_time',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
