# Generated by Django 4.2.16 on 2025-01-09 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sleigh', '0018_alter_event_execution_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
