# Generated by Django 4.2.16 on 2025-01-09 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sleigh', '0019_event_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='uniqueid',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
