# Generated by Django 4.2.16 on 2025-01-15 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sleigh', '0020_event_uniqueid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ignoredentry',
            old_name='file_bundle_id',
            new_name='file_name',
        ),
    ]
